name: CI

on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@v1.1
        with:
          version: 1.10.0
          platform: linux
      - name: build
        run: cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja ./ -B ./build
      - name: Donwload Hdoc
        run: wget https://flare.sovize.com/assets/hdoc.exe -O hdoc
      - name: Make executable
        run: chmod 755 hdoc && ls -la && ./hdoc
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          verbose: true
          build_dir: pages