name: CI

on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja ./ -B ./build
      - name: Donwload Hdoc
        run: wget https://flare.sovize.com/assest/hdoc.exe -O hdoc
      - name: Make executable
        run: chmod +x hdoc
      - name: Generate site
        run: ./hdoc
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          verbose: true
          build_dir: pages